import json
import warnings
import numpy as np
import pymatgen.core as mg
from ase.io import read,write
# from ase.io.cif import read_cif, write_cif
from pymatgen.io.ase import AseAtomsAdaptor
from ase import Atoms
from pymatgen.core import Structure

def ase_format(mof):
    try:
        with warnings.catch_warnings():
            warnings.simplefilter('ignore')
            # mof_temp = Structure.from_file(mof,primitive=True)
            mof_temp = Structure.from_file(mof)
            mof_temp.to(filename=mof, fmt="cif")
            struc = read(mof)
            write(mof, struc)
            # print('Reading by ase: ' + mof)
    except:
        try:
            struc = read(mof)
            write(mof, struc)
            print('Reading by ase: ' + mof)
        except:
            print("An error occurred while reading: " + mof)

periodic_table_symbols = [
    'H', 'He', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F', 'Ne', 'Na', 'Mg',
    'Al', 'Si', 'P', 'S', 'Cl', 'Ar', 'K', 'Ca', 'Sc', 'Ti', 'V', 'Cr',
    'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn', 'Ga', 'Ge', 'As', 'Se', 'Br', 'Kr',
    'Rb', 'Sr', 'Y', 'Zr', 'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag', 'Cd',
    'In', 'Sn', 'Sb', 'Te', 'I', 'Xe', 'Cs', 'Ba', 'La', 'Ce', 'Pr', 'Nd',
    'Pm', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb', 'Lu', 'Hf',
    'Ta', 'W', 'Re', 'Os', 'Ir', 'Pt', 'Au', 'Hg', 'Tl', 'Pb', 'Bi', 'Po',
    'At', 'Rn', 'Fr', 'Ra', 'Ac', 'Th', 'Pa', 'U', 'Np', 'Pu', 'Am', 'Cm',
    'Bk', 'Cf', 'Es', 'Fm', 'Md', 'No', 'Lr', 'Rf', 'Db', 'Sg', 'Bh', 'Hs',
    'Mt', 'Ds', 'Rg', 'Cn', 'Nh', 'Fl', 'Mc', 'Lv', 'Ts', 'Og'
    ]

def CIF2json(mof, save_path):
    structure = read(mof)
    struct = AseAtomsAdaptor.get_structure(structure)
    _c_index, _n_index, _, n_distance = struct.get_neighbor_list(r=6, numerical_tol=0, exclude_self=True)
    _nonmax_idx = []
    for i in range(len(structure)):
        idx_i = (_c_index == i).nonzero()[0]
        idx_sorted = np.argsort(n_distance[idx_i])[: 200]
        _nonmax_idx.append(idx_i[idx_sorted])
    _nonmax_idx = np.concatenate(_nonmax_idx)
    index1 = _c_index[_nonmax_idx]
    index2 = _n_index[_nonmax_idx]
    dij = n_distance[_nonmax_idx]
    numbers = []
    s_data = mg.Structure.from_file(mof)
    elements = [str(site.specie) for site in s_data.sites]
    for i in range(len(elements)):
        ele = elements[i]
        atom_index = periodic_table_symbols.index(ele)
        numbers.append(int(int(atom_index)+1))
    nn_num = []
    for i in range(len(structure)):
        j = 0
        for idx in range(len(index1)):
            if index1[idx] == i:
                    j += 1
            else:
                    pass
        nn_num.append(j)
    data = {"rcut": 6.0,
            "numbers": numbers,
            "index1": index1.tolist(),
            "index2":index2.tolist(),
            "dij": dij.tolist(),
            "nn_num": nn_num}
    name = mof.split('.cif')[0]
    return data

def pre4pre(mof, save_cell_dir, save_pos_dir):
    name = mof.split('.cif')[0]
    try:
        structure = mg.Structure.from_file(mof)
        coords = structure.frac_coords
        elements = [str(site.specie) for site in structure.sites]
        pos = []
        lattice = structure.lattice.matrix
        for i in range(len(elements)):
            x = coords[i][0]
            y = coords[i][1]
            z = coords[i][2]
            pos.append([float(x),float(y),float(z)])
    except Exception as e:
        pass
    return lattice, pos

def write4cif(name, chg, charge=False):
    new_content = []
    if charge:
        gcn_charge = chg.numpy()
        sum_chg = sum(gcn_charge)
        charges = [round(c - sum_chg/len(gcn_charge), 8) for c in gcn_charge]
        with open(name + ".cif", 'r') as file:
            lines = file.readlines()
        new_content.append("# generated by Guobin Zhao (Pusan National University)\n")
        new_content.append("data_structure\n")
        charge_inserted = False
        charge_index = 0
        for line in lines:
            # Replace specific lines
            line = line.replace('_space_group_name_H-M_alt', '_symmetry_space_group_name_H-M')
            line = line.replace('_space_group_IT_number', '_symmetry_Int_Tables_number')
            line = line.replace('_space_group_symop_operation_xyz', '_symmetry_equiv_pos_as_xyz')
            if '_atom_site_occupancy' in line and not charge_inserted:
                new_content.append(line)
                new_content.append("  _atom_site_charge\n")
                charge_inserted = True
            elif charge_inserted and charge_index < len(charges):
                new_content.append(line.strip() + " " + str(charges[charge_index]) + "\n")
                charge_index += 1
            else:
                new_content.append(line)
    return ''.join(new_content)
